(cl:defpackage snake_control-srv
  (:use )
  (:export
   "GETJOINTSTATES"
   "<GETJOINTSTATES-REQUEST>"
   "GETJOINTSTATES-REQUEST"
   "<GETJOINTSTATES-RESPONSE>"
   "GETJOINTSTATES-RESPONSE"
   "GETJOINTTRAJECTORY"
   "<GETJOINTTRAJECTORY-REQUEST>"
   "GETJOINTTRAJECTORY-REQUEST"
   "<GETJOINTTRAJECTORY-RESPONSE>"
   "GETJOINTTRAJECTORY-RESPONSE"
   "PUBLISHJOINTCMDS"
   "<PUBLISHJOINTCMDS-REQUEST>"
   "PUBLISHJOINTCMDS-REQUEST"
   "<PUBLISHJOINTCMDS-RESPONSE>"
   "PUBLISHJOINTCMDS-RESPONSE"
  ))

