// Generated by gencpp from file snake_control/GetJointTrajectory.msg
// DO NOT EDIT!


#ifndef SNAKE_CONTROL_MESSAGE_GETJOINTTRAJECTORY_H
#define SNAKE_CONTROL_MESSAGE_GETJOINTTRAJECTORY_H

#include <ros/service_traits.h>


#include <snake_control/GetJointTrajectoryRequest.h>
#include <snake_control/GetJointTrajectoryResponse.h>


namespace snake_control
{

struct GetJointTrajectory
{

typedef GetJointTrajectoryRequest Request;
typedef GetJointTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointTrajectory
} // namespace snake_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::snake_control::GetJointTrajectory > {
  static const char* value()
  {
    return "65b4f94a94d1ed67169da35a02f33d3f";
  }

  static const char* value(const ::snake_control::GetJointTrajectory&) { return value(); }
};

template<>
struct DataType< ::snake_control::GetJointTrajectory > {
  static const char* value()
  {
    return "snake_control/GetJointTrajectory";
  }

  static const char* value(const ::snake_control::GetJointTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::snake_control::GetJointTrajectoryRequest> should match 
// service_traits::MD5Sum< ::snake_control::GetJointTrajectory > 
template<>
struct MD5Sum< ::snake_control::GetJointTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::snake_control::GetJointTrajectory >::value();
  }
  static const char* value(const ::snake_control::GetJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::snake_control::GetJointTrajectoryRequest> should match 
// service_traits::DataType< ::snake_control::GetJointTrajectory > 
template<>
struct DataType< ::snake_control::GetJointTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::snake_control::GetJointTrajectory >::value();
  }
  static const char* value(const ::snake_control::GetJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::snake_control::GetJointTrajectoryResponse> should match 
// service_traits::MD5Sum< ::snake_control::GetJointTrajectory > 
template<>
struct MD5Sum< ::snake_control::GetJointTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::snake_control::GetJointTrajectory >::value();
  }
  static const char* value(const ::snake_control::GetJointTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::snake_control::GetJointTrajectoryResponse> should match 
// service_traits::DataType< ::snake_control::GetJointTrajectory > 
template<>
struct DataType< ::snake_control::GetJointTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::snake_control::GetJointTrajectory >::value();
  }
  static const char* value(const ::snake_control::GetJointTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SNAKE_CONTROL_MESSAGE_GETJOINTTRAJECTORY_H
