// Generated by gencpp from file snake_control/GetJointStates.msg
// DO NOT EDIT!


#ifndef SNAKE_CONTROL_MESSAGE_GETJOINTSTATES_H
#define SNAKE_CONTROL_MESSAGE_GETJOINTSTATES_H

#include <ros/service_traits.h>


#include <snake_control/GetJointStatesRequest.h>
#include <snake_control/GetJointStatesResponse.h>


namespace snake_control
{

struct GetJointStates
{

typedef GetJointStatesRequest Request;
typedef GetJointStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointStates
} // namespace snake_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::snake_control::GetJointStates > {
  static const char* value()
  {
    return "bc3247c2ebdce0b3b92a25e3910af17e";
  }

  static const char* value(const ::snake_control::GetJointStates&) { return value(); }
};

template<>
struct DataType< ::snake_control::GetJointStates > {
  static const char* value()
  {
    return "snake_control/GetJointStates";
  }

  static const char* value(const ::snake_control::GetJointStates&) { return value(); }
};


// service_traits::MD5Sum< ::snake_control::GetJointStatesRequest> should match 
// service_traits::MD5Sum< ::snake_control::GetJointStates > 
template<>
struct MD5Sum< ::snake_control::GetJointStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::snake_control::GetJointStates >::value();
  }
  static const char* value(const ::snake_control::GetJointStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::snake_control::GetJointStatesRequest> should match 
// service_traits::DataType< ::snake_control::GetJointStates > 
template<>
struct DataType< ::snake_control::GetJointStatesRequest>
{
  static const char* value()
  {
    return DataType< ::snake_control::GetJointStates >::value();
  }
  static const char* value(const ::snake_control::GetJointStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::snake_control::GetJointStatesResponse> should match 
// service_traits::MD5Sum< ::snake_control::GetJointStates > 
template<>
struct MD5Sum< ::snake_control::GetJointStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::snake_control::GetJointStates >::value();
  }
  static const char* value(const ::snake_control::GetJointStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::snake_control::GetJointStatesResponse> should match 
// service_traits::DataType< ::snake_control::GetJointStates > 
template<>
struct DataType< ::snake_control::GetJointStatesResponse>
{
  static const char* value()
  {
    return DataType< ::snake_control::GetJointStates >::value();
  }
  static const char* value(const ::snake_control::GetJointStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SNAKE_CONTROL_MESSAGE_GETJOINTSTATES_H
